import 'dart:ui';
import 'package:theker_app/models/prayer_time_model.dart';
import 'package:theker_app/views/quran_view.dart';
import 'package:theker_app/views/azkary_view.dart';
import 'package:theker_app/models/category_model.dart';
import 'package:theker_app/views/prayer_time_view.dart';
import 'package:theker_app/views/evening_azkar_view.dart';
import 'package:theker_app/views/morning_azkar_view.dart';
import 'package:theker_app/models/second_category_model.dart';

const kPrimaryColor = Color(0xff007D45);
const kPrimaryFont = 'Marhey';
const kSecondaryFont = 'Tajawal';
const kAzkarBox = 'Azkar';
const kAppBarFontSize = 18.0;
const kHight1 = 20.0;
const kHight2 = 30.0;
const kHight3 = 10.0;

const kNotAccept =
    'روى مسلم عن عُقْبَةَ بْنَ عَامِرٍ الْجُهَنِيَّ يَقُولُ : ثَلاثُ سَاعَاتٍ كَانَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ يَنْهَانَا أَنْ نُصَلِّيَ فِيهِنَّ أَوْ أَنْ نَقْبُرَ فِيهِنَّ مَوْتَانَا: حِينَ تَطْلُعُ الشَّمْسُ بَازِغَةً حَتَّى تَرْتَفِعَ، وَحِينَ يَقُومُ قَائِمُ الظَّهِيرَةِ حَتَّى تَمِيلَ الشَّمْسُ، وَحِينَ تَضَيَّفُ الشَّمْسُ لِلْغُرُوبِ حَتَّى تَغْرُبَ .';
const kSonan1 =
    'عن أم حبيبة -رضي الله عنها- الثابت في صحيح مسلم أن النبي -صلى الله عليه وسلم- قال: ما من عبد مسلم يصلي لله كل يوم اثنتي عشرة ركعة تطوعا غير فريضة، إلا بنى الله له بيتا في الجنة.';
const kSonan2 =
    'وعن عائشة -رضي الله عنها- قالت: قال رسول الله صلى الله عليه وسلم: من ثابر على ثنتي عشرة ركعة من السنة؛ بنى الله له بيتا في الجنة: أربع ركعات قبل الظهر، وركعتين بعدها، وركعتين بعد المغرب، وركعتين بعد العشاء، وركعتين قبل الفجر.';
const kSalahHal =
    ' يا حي يا قيوم برحمتك أستغيث أصلح لي شأني كله ولا تكلني إلي نفسى طرفة عين لا إله إلا أنت';
const kNeamaAfia =
    'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ زَوَالِ نِعْمَتِكَ، وَتَحَوُّلِ عَافِيَتِكَ، وَفُجَاءَةِ نِقْمَتِكَ، وَجَمِيعِ سَخَطِكَ';
const kSayedEstagfar =
    'اللَّهُمَّ أَنْتَ رَبِّي لاَ إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا   عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ لَكَ بِذَنْبِي فَاغْفِرْ لِي، إِنَّهُ لاَ يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ.';
const kFajrHadth =
    'قال رسول الله صلى الله عليه وسلم: (مَن صَلَّى الصُّبْحَ فَهو في ذِمَّةِ اللهِ، فلا يَطْلُبَنَّكُمُ اللَّهُ مِن ذِمَّتِهِ بشيءٍ فيُدْرِكَهُ فَيَكُبَّهُ في نَارِ جَهَنَّمَ).';
const List<CategoryModel> categoryModel = [
  CategoryModel(
    targetPage: PrayerTimeView(),
    image: 'assets/images/categories_images/Vector.png',
    name: 'أذكار بعد الصلاة',
  ),
  CategoryModel(
    targetPage: AzkarView(),
    image: 'assets/images/categories_images/Vector.png',
    name: 'أذكاري',
  ),
  CategoryModel(
    targetPage: QuranView(),
    image: 'assets/images/categories_images/Vector.png',
    name: 'أذكار النوم',
  ),
  CategoryModel(
    targetPage: MorningAzkarView(),
    image: 'assets/images/categories_images/Vector.png',
    name: 'أذكار الصباح',
  ),
  CategoryModel(
    targetPage: AzkarView(),
    image: 'assets/images/categories_images/Vector.png',
    name: 'أذكار الإستيقاظ',
  ),
  CategoryModel(
    targetPage: EveningAzkarView(),
    image: 'assets/images/categories_images/Vector.png',
    name: 'أذكار المساء',
  ),
  CategoryModel(
    targetPage: AzkarView(),
    image: 'assets/images/categories_images/Vector.png',
    name: 'أدعية شاملة',
  ),
  CategoryModel(
    targetPage: AzkarView(),
    image: 'assets/images/categories_images/Vector.png',
    name: 'الرقية الشرعية',
  ),
];

const List<Map<String, dynamic>> surahsList = [
  {
    "number": 1,
    "name": " ٱلْفَاتِحَةِ",
    "englishName": "Al-Faatiha",
    "englishNameTranslation": "The Opening",
    "numberOfAyahs": 7,
    "revelationType": "مكية",
    "startPage": 1,
  },
  {
    "number": 2,
    "name": " البَقَرَةِ",
    "englishName": "Al-Baqara",
    "englishNameTranslation": "The Cow",
    "numberOfAyahs": 286,
    "revelationType": "مدنية",
    "startPage": 2,
  },
  {
    "number": 3,
    "name": " آلِ عِمۡرَانَ",
    "englishName": "Aal-i-Imraan",
    "englishNameTranslation": "The Family of Imraan",
    "numberOfAyahs": 200,
    "revelationType": "مدنية",
    "startPage": 50,
  },
  {
    "number": 4,
    "name": " النِّسَاءِ",
    "englishName": "An-Nisaa",
    "englishNameTranslation": "The Women",
    "numberOfAyahs": 176,
    "revelationType": "مدنية",
    "startPage": 77,
  },
  {
    "number": 5,
    "name": " المَائـِدَةِ",
    "englishName": "Al-Maaida",
    "englishNameTranslation": "The Table",
    "numberOfAyahs": 120,
    "revelationType": "مدنية",
    "startPage": 106,
  },
  {
    "number": 6,
    "name": " الأَنۡعَامِ",
    "englishName": "Al-An'aam",
    "englishNameTranslation": "The Cattle",
    "numberOfAyahs": 165,
    "revelationType": "مكية",
    "startPage": 128,
  },
  {
    "number": 7,
    "name": " الأَعۡرَافِ",
    "englishName": "Al-A'raaf",
    "englishNameTranslation": "The Heights",
    "numberOfAyahs": 206,
    "revelationType": "مكية",
    "startPage": 151,
  },
  {
    "number": 8,
    "name": " الأَنفَالِ",
    "englishName": "Al-Anfaal",
    "englishNameTranslation": "The Spoils of War",
    "numberOfAyahs": 75,
    "revelationType": "مدنية",
    "startPage": 177,
  },
  {
    "number": 9,
    "name": " التَّوۡبَةِ",
    "englishName": "At-Tawba",
    "englishNameTranslation": "The Repentance",
    "numberOfAyahs": 129,
    "revelationType": "مدنية",
    "startPage": 187,
  },
  {
    "number": 10,
    "name": " يُونُسَ",
    "englishName": "Yunus",
    "englishNameTranslation": "Jonas",
    "numberOfAyahs": 109,
    "revelationType": "مكية",
    "startPage": 208,
  },
  {
    "number": 11,
    "name": " هُودٍ",
    "englishName": "Hud",
    "englishNameTranslation": "Hud",
    "numberOfAyahs": 123,
    "revelationType": "مكية",
    "startPage": 221,
  },
  {
    "number": 12,
    "name": " يُوسُفَ",
    "englishName": "Yusuf",
    "englishNameTranslation": "Joseph",
    "numberOfAyahs": 111,
    "revelationType": "مكية",
    "startPage": 235,
  },
  {
    "number": 13,
    "name": " الرَّعۡدِ",
    "englishName": "Ar-Ra'd",
    "englishNameTranslation": "The Thunder",
    "numberOfAyahs": 43,
    "revelationType": "مدنية",
    "startPage": 249,
  },
  {
    "number": 14,
    "name": " إِبۡرَاهِيمَ",
    "englishName": "Ibrahim",
    "englishNameTranslation": "Abraham",
    "numberOfAyahs": 52,
    "revelationType": "مكية",
    "startPage": 255,
  },
  {
    "number": 15,
    "name": " الحِجۡرِ",
    "englishName": "Al-Hijr",
    "englishNameTranslation": "The Rock",
    "numberOfAyahs": 99,
    "revelationType": "مكية",
    "startPage": 262,
  },
  {
    "number": 16,
    "name": " النَّحۡلِ",
    "englishName": "An-Nahl",
    "englishNameTranslation": "The Bee",
    "numberOfAyahs": 128,
    "revelationType": "مكية",
    "startPage": 267,
  },
  {
    "number": 17,
    "name": " الإِسۡرَاءِ",
    "englishName": "Al-Israa",
    "englishNameTranslation": "The Night Journey",
    "numberOfAyahs": 111,
    "revelationType": "مكية",
    "startPage": 282,
  },
  {
    "number": 18,
    "name": " الكَهۡفِ",
    "englishName": "Al-Kahf",
    "englishNameTranslation": "The Cave",
    "numberOfAyahs": 110,
    "revelationType": "مكية",
    "startPage": 293,
  },
  {
    "number": 19,
    "name": " مَرۡيَمَ",
    "englishName": "Maryam",
    "englishNameTranslation": "Mary",
    "numberOfAyahs": 98,
    "revelationType": "مكية",
    "startPage": 305,
  },
  {
    "number": 20,
    "name": " طه",
    "englishName": "Taa-Haa",
    "englishNameTranslation": "Taa-Haa",
    "numberOfAyahs": 135,
    "revelationType": "مكية",
    "startPage": 312,
  },
  {
    "number": 21,
    "name": " الأَنبِيَاءِ",
    "englishName": "Al-Anbiyaa",
    "englishNameTranslation": "The Prophets",
    "numberOfAyahs": 112,
    "revelationType": "مكية",
    "startPage": 322,
  },
  {
    "number": 22,
    "name": " الحَجِّ",
    "englishName": "Al-Hajj",
    "englishNameTranslation": "The Pilgrimage",
    "numberOfAyahs": 78,
    "revelationType": "مدنية",
    "startPage": 332,
  },
  {
    "number": 23,
    "name": " المُؤۡمِنُونَ",
    "englishName": "Al-Muminoon",
    "englishNameTranslation": "The Believers",
    "numberOfAyahs": 118,
    "revelationType": "مكية",
    "startPage": 342,
  },
  {
    "number": 24,
    "name": " النُّورِ",
    "englishName": "An-Noor",
    "englishNameTranslation": "The Light",
    "numberOfAyahs": 64,
    "revelationType": "مدنية",
    "startPage": 350,
  },
  {
    "number": 25,
    "name": " الفُرۡقَانِ",
    "englishName": "Al-Furqaan",
    "englishNameTranslation": "The Criterion",
    "numberOfAyahs": 77,
    "revelationType": "مكية",
    "startPage": 359,
  },
  {
    "number": 26,
    "name": " الشُّعَرَاءِ",
    "englishName": "Ash-Shu'araa",
    "englishNameTranslation": "The Poets",
    "numberOfAyahs": 227,
    "revelationType": "مكية",
    "startPage": 367,
  },
  {
    "number": 27,
    "name": " النَّمۡلِ",
    "englishName": "An-Naml",
    "englishNameTranslation": "The Ant",
    "numberOfAyahs": 93,
    "revelationType": "مكية",
    "startPage": 377,
  },
  {
    "number": 28,
    "name": " القَصَصِ",
    "englishName": "Al-Qasas",
    "englishNameTranslation": "The Stories",
    "numberOfAyahs": 88,
    "revelationType": "مكية",
    "startPage": 385,
  },
  {
    "number": 29,
    "name": " العَنكَبُوتِ",
    "englishName": "Al-Ankaboot",
    "englishNameTranslation": "The Spider",
    "numberOfAyahs": 69,
    "revelationType": "مكية",
    "startPage": 396,
  },
  {
    "number": 30,
    "name": " الرُّومِ",
    "englishName": "Ar-Room",
    "englishNameTranslation": "The Romans",
    "numberOfAyahs": 60,
    "revelationType": "مكية",
    "startPage": 404,
  },
  {
    "number": 31,
    "name": " لُقۡمَانَ",
    "englishName": "Luqman",
    "englishNameTranslation": "Luqman",
    "numberOfAyahs": 34,
    "revelationType": "مكية",
    "startPage": 411,
  },
  {
    "number": 32,
    "name": " السَّجۡدَةِ",
    "englishName": "As-Sajda",
    "englishNameTranslation": "The Prostration",
    "numberOfAyahs": 30,
    "revelationType": "مكية",
    "startPage": 415,
  },
  {
    "number": 33,
    "name": " الأَحۡزَابِ",
    "englishName": "Al-Ahzaab",
    "englishNameTranslation": "The Clans",
    "numberOfAyahs": 73,
    "revelationType": "مدنية",
    "startPage": 418,
  },
  {
    "number": 34,
    "name": " سَبَإٍ",
    "englishName": "Saba",
    "englishNameTranslation": "Sheba",
    "numberOfAyahs": 54,
    "revelationType": "مكية",
    "startPage": 428,
  },
  {
    "number": 35,
    "name": " فَاطِرٍ",
    "englishName": "Faatir",
    "englishNameTranslation": "The Originator",
    "numberOfAyahs": 45,
    "revelationType": "مكية",
    "startPage": 434,
  },
  {
    "number": 36,
    "name": " يسٓ",
    "englishName": "Yaseen",
    "englishNameTranslation": "Yaseen",
    "numberOfAyahs": 83,
    "revelationType": "مكية",
    "startPage": 440,
  },
  {
    "number": 37,
    "name": " الصَّافَّاتِ",
    "englishName": "As-Saaffaat",
    "englishNameTranslation": "Those drawn up in Ranks",
    "numberOfAyahs": 182,
    "revelationType": "مكية",
    "startPage": 446,
  },
  {
    "number": 38,
    "name": " صٓ",
    "englishName": "Saad",
    "englishNameTranslation": "The letter Saad",
    "numberOfAyahs": 88,
    "revelationType": "مكية",
    "startPage": 453,
  },
  {
    "number": 39,
    "name": " الزُّمَرِ",
    "englishName": "Az-Zumar",
    "englishNameTranslation": "The Groups",
    "numberOfAyahs": 75,
    "revelationType": "مكية",
    "startPage": 458,
  },
  {
    "number": 40,
    "name": " غَافِرٍ",
    "englishName": "Ghafir",
    "englishNameTranslation": "The Forgiver",
    "numberOfAyahs": 85,
    "revelationType": "مكية",
    "startPage": 467,
  },
  {
    "number": 41,
    "name": " فُصِّلَتۡ",
    "englishName": "Fussilat",
    "englishNameTranslation": "Explained in detail",
    "numberOfAyahs": 54,
    "revelationType": "مكية",
    "startPage": 477,
  },
  {
    "number": 42,
    "name": " الشُّورَىٰ",
    "englishName": "Ash-Shura",
    "englishNameTranslation": "Consultation",
    "numberOfAyahs": 53,
    "revelationType": "مكية",
    "startPage": 482,
  },
  {
    "number": 43,
    "name": " الزُّخۡرُفِ",
    "englishName": "Az-Zukhruf",
    "englishNameTranslation": "Ornaments of gold",
    "numberOfAyahs": 89,
    "revelationType": "مكية",
    "startPage": 489,
  },
  {
    "number": 44,
    "name": " الدُّخَانِ",
    "englishName": "Ad-Dukhaan",
    "englishNameTranslation": "The Smoke",
    "numberOfAyahs": 59,
    "revelationType": "مكية",
    "startPage": 496,
  },
  {
    "number": 45,
    "name": " الجَاثِيَةِ",
    "englishName": "Al-Jaathiya",
    "englishNameTranslation": "Crouching",
    "numberOfAyahs": 37,
    "revelationType": "مكية",
    "startPage": 499,
  },
  {
    "number": 46,
    "name": " الأَحۡقَافِ",
    "englishName": "Al-Ahqaf",
    "englishNameTranslation": "The Dunes",
    "numberOfAyahs": 35,
    "revelationType": "مكية",
    "startPage": 502,
  },
  {
    "number": 47,
    "name": " مُحَمَّدٍ",
    "englishName": "Muhammad",
    "englishNameTranslation": "Muhammad",
    "numberOfAyahs": 38,
    "revelationType": "مدنية",
    "startPage": 507,
  },
  {
    "number": 48,
    "name": " الفَتۡحِ",
    "englishName": "Al-Fath",
    "englishNameTranslation": "The Victory",
    "numberOfAyahs": 29,
    "revelationType": "مدنية",
    "startPage": 511,
  },
  {
    "number": 49,
    "name": " الحُجُرَاتِ",
    "englishName": "Al-Hujuraat",
    "englishNameTranslation": "The Inner Apartments",
    "numberOfAyahs": 18,
    "revelationType": "مدنية",
    "startPage": 515,
  },
  {
    "number": 50,
    "name": " قٓ",
    "englishName": "Qaaf",
    "englishNameTranslation": "The letter Qaaf",
    "numberOfAyahs": 45,
    "revelationType": "مكية",
    "startPage": 518,
  },
  {
    "number": 51,
    "name": " الذَّارِيَاتِ",
    "englishName": "Adh-Dhaariyat",
    "englishNameTranslation": "The Winnowing Winds",
    "numberOfAyahs": 60,
    "revelationType": "مكية",
    "startPage": 520,
  },
  {
    "number": 52,
    "name": " الطُّورِ",
    "englishName": "At-Tur",
    "englishNameTranslation": "The Mount",
    "numberOfAyahs": 49,
    "revelationType": "مكية",
    "startPage": 523,
  },
  {
    "number": 53,
    "name": " النَّجۡمِ",
    "englishName": "An-Najm",
    "englishNameTranslation": "The Star",
    "numberOfAyahs": 62,
    "revelationType": "مكية",
    "startPage": 526,
  },
  {
    "number": 54,
    "name": " القَمَرِ",
    "englishName": "Al-Qamar",
    "englishNameTranslation": "The Moon",
    "numberOfAyahs": 55,
    "revelationType": "مكية",
    "startPage": 528,
  },
  {
    "number": 55,
    "name": " الرَّحۡمَٰن",
    "englishName": "Ar-Rahmaan",
    "englishNameTranslation": "The Beneficent",
    "numberOfAyahs": 78,
    "revelationType": "مدنية",
    "startPage": 531,
  },
  {
    "number": 56,
    "name": " الوَاقِعَةِ",
    "englishName": "Al-Waaqia",
    "englishNameTranslation": "The Inevitable",
    "numberOfAyahs": 96,
    "revelationType": "مكية",
    "startPage": 534,
  },
  {
    "number": 57,
    "name": " الحَدِيدِ",
    "englishName": "Al-Hadid",
    "englishNameTranslation": "The Iron",
    "numberOfAyahs": 29,
    "revelationType": "مدنية",
    "startPage": 537,
  },
  {
    "number": 58,
    "name": " المُجَادلَةِ",
    "englishName": "Al-Mujaadila",
    "englishNameTranslation": "The Pleading Woman",
    "numberOfAyahs": 22,
    "revelationType": "مدنية",
    "startPage": 542,
  },
  {
    "number": 59,
    "name": " الحَشۡرِ",
    "englishName": "Al-Hashr",
    "englishNameTranslation": "The Exile",
    "numberOfAyahs": 24,
    "revelationType": "مدنية",
    "startPage": 545,
  },
  {
    "number": 60,
    "name": " المُمۡتَحنَةِ",
    "englishName": "Al-Mumtahana",
    "englishNameTranslation": "She that is to be examined",
    "numberOfAyahs": 13,
    "revelationType": "مدنية",
    "startPage": 549,
  },
  {
    "number": 61,
    "name": " الصَّفِّ",
    "englishName": "As-Saff",
    "englishNameTranslation": "The Ranks",
    "numberOfAyahs": 14,
    "revelationType": "مدنية",
    "startPage": 551,
  },
  {
    "number": 62,
    "name": " الجُمُعَةِ",
    "englishName": "Al-Jumu'a",
    "englishNameTranslation": "Friday",
    "numberOfAyahs": 11,
    "revelationType": "مدنية",
    "startPage": 553,
  },
  {
    "number": 63,
    "name": " المُنَافِقُونَ",
    "englishName": "Al-Munaafiqoon",
    "englishNameTranslation": "The Hypocrites",
    "numberOfAyahs": 11,
    "revelationType": "مدنية",
    "startPage": 554,
  },
  {
    "number": 64,
    "name": " التَّغَابُنِ",
    "englishName": "At-Taghaabun",
    "englishNameTranslation": "Mutual Disillusion",
    "numberOfAyahs": 18,
    "revelationType": "مدنية",
    "startPage": 556,
  },
  {
    "number": 65,
    "name": " الطَّلَاقِ",
    "englishName": "At-Talaaq",
    "englishNameTranslation": "Divorce",
    "numberOfAyahs": 12,
    "revelationType": "مدنية",
    "startPage": 558,
  },
  {
    "number": 66,
    "name": " التَّحۡرِيمِ",
    "englishName": "At-Tahrim",
    "englishNameTranslation": "The Prohibition",
    "numberOfAyahs": 12,
    "revelationType": "مدنية",
    "startPage": 560,
  },
  {
    "number": 67,
    "name": " المُلۡكِ",
    "englishName": "Al-Mulk",
    "englishNameTranslation": "The Sovereignty",
    "numberOfAyahs": 30,
    "revelationType": "مكية",
    "startPage": 562,
  },
  {
    "number": 68,
    "name": " القَلَمِ",
    "englishName": "Al-Qalam",
    "englishNameTranslation": "The Pen",
    "numberOfAyahs": 52,
    "revelationType": "مكية",
    "startPage": 564,
  },
  {
    "number": 69,
    "name": " الحَاقَّةِ",
    "englishName": "Al-Haaqqa",
    "englishNameTranslation": "The Reality",
    "numberOfAyahs": 52,
    "revelationType": "مكية",
    "startPage": 566,
  },
  {
    "number": 70,
    "name": " المَعَارِجِ",
    "englishName": "Al-Ma'aarij",
    "englishNameTranslation": "The Ascending Stairways",
    "numberOfAyahs": 44,
    "revelationType": "مكية",
    "startPage": 568,
  },
  {
    "number": 71,
    "name": " نُوحٍ",
    "englishName": "Nooh",
    "englishNameTranslation": "Noah",
    "numberOfAyahs": 28,
    "revelationType": "مكية",
    "startPage": 570,
  },
  {
    "number": 72,
    "name": " الجِنِّ",
    "englishName": "Al-Jinn",
    "englishNameTranslation": "The Jinn",
    "numberOfAyahs": 28,
    "revelationType": "مكية",
    "startPage": 572,
  },
  {
    "number": 73,
    "name": " المُزَّمِّلِ",
    "englishName": "Al-Muzzammil",
    "englishNameTranslation": "The Enshrouded One",
    "numberOfAyahs": 20,
    "revelationType": "مكية",
    "startPage": 574,
  },
  {
    "number": 74,
    "name": " المُدَّثِّرِ",
    "englishName": "Al-Muddaththir",
    "englishNameTranslation": "The Cloaked One",
    "numberOfAyahs": 56,
    "revelationType": "مكية",
    "startPage": 575,
  },
  {
    "number": 75,
    "name": " القِيَامَةِ",
    "englishName": "Al-Qiyaama",
    "englishNameTranslation": "The Resurrection",
    "numberOfAyahs": 40,
    "revelationType": "مكية",
    "startPage": 577,
  },
  {
    "number": 76,
    "name": " الإِنسَانِ",
    "englishName": "Al-Insaan",
    "englishNameTranslation": "Man",
    "numberOfAyahs": 31,
    "revelationType": "مدنية",
    "startPage": 578,
  },
  {
    "number": 77,
    "name": " المُرۡسَلَاتِ",
    "englishName": "Al-Mursalaat",
    "englishNameTranslation": "The Emissaries",
    "numberOfAyahs": 50,
    "revelationType": "مكية",
    "startPage": 580,
  },
  {
    "number": 78,
    "name": " النَّبَإِ",
    "englishName": "An-Naba",
    "englishNameTranslation": "The Announcement",
    "numberOfAyahs": 40,
    "revelationType": "مكية",
    "startPage": 582,
  },
  {
    "number": 79,
    "name": " النَّازِعَاتِ",
    "englishName": "An-Naazi'aat",
    "englishNameTranslation": "Those who drag forth",
    "numberOfAyahs": 46,
    "revelationType": "مكية",
    "startPage": 583,
  },
  {
    "number": 80,
    "name": " عَبَسَ",
    "englishName": "Abasa",
    "englishNameTranslation": "He frowned",
    "numberOfAyahs": 42,
    "revelationType": "مكية",
    "startPage": 585,
  },
  {
    "number": 81,
    "name": " التَّكۡوِيرِ",
    "englishName": "At-Takwir",
    "englishNameTranslation": "The Overthrowing",
    "numberOfAyahs": 29,
    "revelationType": "مكية",
    "startPage": 586,
  },
  {
    "number": 82,
    "name": " الانفِطَارِ",
    "englishName": "Al-Infitaar",
    "englishNameTranslation": "The Cleaving",
    "numberOfAyahs": 19,
    "revelationType": "مكية",
    "startPage": 587,
  },
  {
    "number": 83,
    "name": " المُطَفِّفِينَ",
    "englishName": "Al-Mutaffifin",
    "englishNameTranslation": "Defrauding",
    "numberOfAyahs": 36,
    "revelationType": "مكية",
    "startPage": 587,
  },
  {
    "number": 84,
    "name": " الانشِقَاقِ",
    "englishName": "Al-Inshiqaaq",
    "englishNameTranslation": "The Splitting Open",
    "numberOfAyahs": 25,
    "revelationType": "مكية",
    "startPage": 589,
  },
  {
    "number": 85,
    "name": " البُرُوجِ",
    "englishName": "Al-Burooj",
    "englishNameTranslation": "The Constellations",
    "numberOfAyahs": 22,
    "revelationType": "مكية",
    "startPage": 590,
  },
  {
    "number": 86,
    "name": " الطَّارِقِ",
    "englishName": "At-Taariq",
    "englishNameTranslation": "The Morning Star",
    "numberOfAyahs": 17,
    "revelationType": "مكية",
    "startPage": 591,
  },
  {
    "number": 87,
    "name": " الأَعۡلَىٰ",
    "englishName": "Al-A'laa",
    "englishNameTranslation": "The Most High",
    "numberOfAyahs": 19,
    "revelationType": "مكية",
    "startPage": 591,
  },
  {
    "number": 88,
    "name": " الغَاشِيَةِ",
    "englishName": "Al-Ghaashiya",
    "englishNameTranslation": "The Overwhelming",
    "numberOfAyahs": 26,
    "revelationType": "مكية",
    "startPage": 592,
  },
  {
    "number": 89,
    "name": " الفَجۡرِ",
    "englishName": "Al-Fajr",
    "englishNameTranslation": "The Dawn",
    "numberOfAyahs": 30,
    "revelationType": "مكية",
    "startPage": 593,
  },
  {
    "number": 90,
    "name": " البَلَدِ",
    "englishName": "Al-Balad",
    "englishNameTranslation": "The City",
    "numberOfAyahs": 20,
    "revelationType": "مكية",
    "startPage": 594,
  },
  {
    "number": 91,
    "name": " الشَّمۡسِ",
    "englishName": "Ash-Shams",
    "englishNameTranslation": "The Sun",
    "numberOfAyahs": 15,
    "revelationType": "مكية",
    "startPage": 595,
  },
  {
    "number": 92,
    "name": " اللَّيۡلِ",
    "englishName": "Al-Lail",
    "englishNameTranslation": "The Night",
    "numberOfAyahs": 21,
    "revelationType": "مكية",
    "startPage": 595,
  },
  {
    "number": 93,
    "name": " الضُّحَىٰ",
    "englishName": "Ad-Dhuhaa",
    "englishNameTranslation": "The Morning Hours",
    "numberOfAyahs": 11,
    "revelationType": "مكية",
    "startPage": 596,
  },
  {
    "number": 94,
    "name": " الشَّرۡحِ",
    "englishName": "Ash-Sharh",
    "englishNameTranslation": "The Consolation",
    "numberOfAyahs": 8,
    "revelationType": "مكية",
    "startPage": 596,
  },
  {
    "number": 95,
    "name": " التِّينِ",
    "englishName": "At-Tin",
    "englishNameTranslation": "The Fig",
    "numberOfAyahs": 8,
    "revelationType": "مكية",
    "startPage": 597,
  },
  {
    "number": 96,
    "name": " العَلَقِ",
    "englishName": "Al-Alaq",
    "englishNameTranslation": "The Clot",
    "numberOfAyahs": 19,
    "revelationType": "مكية",
    "startPage": 597,
  },
  {
    "number": 97,
    "name": " القَدۡرِ",
    "englishName": "Al-Qadr",
    "englishNameTranslation": "The Power, Fate",
    "numberOfAyahs": 5,
    "revelationType": "مكية",
    "startPage": 598,
  },
  {
    "number": 98,
    "name": " البَيِّنَةِ",
    "englishName": "Al-Bayyina",
    "englishNameTranslation": "The Evidence",
    "numberOfAyahs": 8,
    "revelationType": "مدنية",
    "startPage": 598,
  },
  {
    "number": 99,
    "name": " الزَّلۡزَلَةِ",
    "englishName": "Az-Zalzala",
    "englishNameTranslation": "The Earthquake",
    "numberOfAyahs": 8,
    "revelationType": "مدنية",
    "startPage": 599,
  },
  {
    "number": 100,
    "name": " العَادِيَاتِ",
    "englishName": "Al-Aadiyaat",
    "englishNameTranslation": "The Chargers",
    "numberOfAyahs": 11,
    "revelationType": "مكية",
    "startPage": 599,
  },
  {
    "number": 101,
    "name": " القَارِعَةِ",
    "englishName": "Al-Qaari'a",
    "englishNameTranslation": "The Calamity",
    "numberOfAyahs": 11,
    "revelationType": "مكية",
    "startPage": 600,
  },
  {
    "number": 102,
    "name": " التَّكَاثُرِ",
    "englishName": "At-Takaathur",
    "englishNameTranslation": "Competition",
    "numberOfAyahs": 8,
    "revelationType": "مكية",
    "startPage": 600,
  },
  {
    "number": 103,
    "name": " العَصۡرِ",
    "englishName": "Al-Asr",
    "englishNameTranslation": "The Declining Day, Epoch",
    "numberOfAyahs": 3,
    "revelationType": "مكية",
    "startPage": 601,
  },
  {
    "number": 104,
    "name": " الهُمَزَةِ",
    "englishName": "Al-Humaza",
    "englishNameTranslation": "The Traducer",
    "numberOfAyahs": 9,
    "revelationType": "مكية",
    "startPage": 601,
  },
  {
    "number": 105,
    "name": " الفِيلِ",
    "englishName": "Al-Fil",
    "englishNameTranslation": "The Elephant",
    "numberOfAyahs": 5,
    "revelationType": "مكية",
    "startPage": 602,
  },
  {
    "number": 106,
    "name": " قُرَيۡشٍ",
    "englishName": "Quraish",
    "englishNameTranslation": "Quraysh",
    "numberOfAyahs": 4,
    "revelationType": "مكية",
    "startPage": 602,
  },
  {
    "number": 107,
    "name": " المَاعُونِ",
    "englishName": "Al-Maa'un",
    "englishNameTranslation": "Almsgiving",
    "numberOfAyahs": 7,
    "revelationType": "مكية",
    "startPage": 603,
  },
  {
    "number": 108,
    "name": " الكَوۡثَرِ",
    "englishName": "Al-Kawthar",
    "englishNameTranslation": "Abundance",
    "numberOfAyahs": 3,
    "revelationType": "مكية",
    "startPage": 603,
  },
  {
    "number": 109,
    "name": " الكَافِرُونَ",
    "englishName": "Al-Kaafiroon",
    "englishNameTranslation": "The Disbelievers",
    "numberOfAyahs": 6,
    "revelationType": "مكية",
    "startPage": 604,
  },
  {
    "number": 110,
    "name": " النَّصۡرِ",
    "englishName": "An-Nasr",
    "englishNameTranslation": "Divine Support",
    "numberOfAyahs": 3,
    "revelationType": "مدنية",
    "startPage": 604,
  },
  {
    "number": 111,
    "name": " المَسَدِ",
    "englishName": "Al-Masad",
    "englishNameTranslation": "The Palm Fibre",
    "numberOfAyahs": 5,
    "revelationType": "مكية",
    "startPage": 605,
  },
  {
    "number": 112,
    "name": " الإِخۡلَاصِ",
    "englishName": "Al-Ikhlaas",
    "englishNameTranslation": "Sincerity",
    "numberOfAyahs": 4,
    "revelationType": "مكية",
    "startPage": 605,
  },
  {
    "number": 113,
    "name": " الفَلَقِ",
    "englishName": "Al-Falaq",
    "englishNameTranslation": "The Dawn",
    "numberOfAyahs": 5,
    "revelationType": "مكية",
    "startPage": 606,
  },
  {
    "number": 114,
    "name": " النَّاسِ",
    "englishName": "An-Naas",
    "englishNameTranslation": "Mankind",
    "numberOfAyahs": 6,
    "revelationType": "مكية",
    "startPage": 606,
  },
];

List<String> pageImagePath = List.generate(604, (index) => '${index + 1}.png');

final List<SecondCategoryModel> catygories = const [
  SecondCategoryModel(
    imagePath: 'assets/images/on_boarding_view_images/qurann.png',
    title: 'المصحف',
    subtitle: 'اقرأ القرأن الكريم, نظم وردك اليومي, وحدد مدة ختمتك',
    textButton: 'استمر',
  ),
  SecondCategoryModel(
    imagePath: 'assets/images/on_boarding_view_images/prayerrrs.png',
    title: 'مواقيت الصلاة',
    subtitle: 'تابع مواقيت الصلاة بدقة اينما كنت, مع تنبيهات لكل صلاة',
    textButton: 'استمر',
  ),
  SecondCategoryModel(
    imagePath: 'assets/images/on_boarding_view_images/azkaree.png',
    title: 'أذكاري',
    subtitle:
        'مجموعة من الاذكار اليوميه, بالاضافه الى مكان للاحتفاظ باذكارك الخاصه',
    textButton: 'استمر',
  ),
  SecondCategoryModel(
    imagePath: 'assets/images/on_boarding_view_images/qiblaaa.png',
    title: 'القبلة',
    subtitle: 'تحديد اتجاه القبله بدقه في اي وقت واي مكان',
    textButton: 'استمر',
  ),
  SecondCategoryModel(
    imagePath: 'assets/images/on_boarding_view_images/explorrrree.png',
    title: 'استكشف المزيد',
    subtitle: 'إستخدم التطبيق واكتشف المزيد من المزايا',
    textButton: 'إبدأ',
  ),
];

final List<String> notAcceptList = const [
  '1 - من طلوع الفجر الصادق حتى تطلع الشمس',
  '2 - من طلوع الشمس حتى ترتفع قيد رمح.',
  '3- من بعد صلاة العصر، حتى تميل إلى الغروب.',
  '4- من حين تميل الشمس للغروب حتى تغرب.',
  '5- حين يقومُ قائم الظهيرة، وتتوسط الشمس كبد السماء.',
];
